/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Raiga' at '22/09/12 18:27' with Gradle 2.1
 *
 * @author Raiga, @date 22/09/12 18:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
